<script setup lang="ts">
import { onMounted } from 'vue'
import { useReportsStore } from '@/stores/reports'
import ReportList from '@/components/reports/ReportList.vue'
import SkeletonBlock from '@/components/common/SkeletonBlock.vue'

const store = useReportsStore()

onMounted(() => {
  store.fetchReports()
})
</script>

<template>
  <div>
    <!-- Page header -->
    <div class="pb-6 mb-8 border-b border-border">
      <h2 class="font-mono text-2xl font-bold uppercase tracking-wider text-text-primary">Reports</h2>
      <p class="font-sans text-sm text-text-secondary mt-1">Incident reports generated by the agent</p>
    </div>

    <!-- Skeleton loader -->
    <div v-if="store.loading" class="space-y-3">
      <div v-for="n in 3" :key="n" class="border border-border rounded-lg bg-bg-surface p-6 space-y-3">
        <SkeletonBlock width="70%" height="1rem" />
        <SkeletonBlock width="40%" height="0.75rem" />
      </div>
    </div>
    <div v-else-if="store.reports.length === 0" class="text-text-muted text-sm font-mono">
      No reports yet.
    </div>
    <ReportList v-else :reports="store.reports" />
  </div>
</template>
