<script setup lang="ts">
import { onMounted } from 'vue'
import { useReportsStore } from '@/stores/reports'
import ReportList from '@/components/reports/ReportList.vue'
import LoadingSpinner from '@/components/common/LoadingSpinner.vue'

const store = useReportsStore()

onMounted(() => {
  store.fetchReports()
})
</script>

<template>
  <div>
    <!-- Page header -->
    <div class="pb-6 mb-8 border-b border-border">
      <h2 class="font-mono text-2xl font-bold uppercase tracking-wider text-text-primary">Reports</h2>
      <p class="font-sans text-sm text-text-secondary mt-1">Incident reports generated by the agent</p>
    </div>

    <LoadingSpinner v-if="store.loading" />
    <div v-else-if="store.reports.length === 0" class="text-text-muted text-sm font-mono">
      No reports yet.
    </div>
    <ReportList v-else :reports="store.reports" />
  </div>
</template>
