// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_config.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAgentConfig = `-- name: GetAgentConfig :one
SELECT id, model, mode, schedule, system_prompt_override, created_at, updated_at FROM agent_config LIMIT 1
`

func (q *Queries) GetAgentConfig(ctx context.Context) (AgentConfig, error) {
	row := q.db.QueryRow(ctx, getAgentConfig)
	var i AgentConfig
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Mode,
		&i.Schedule,
		&i.SystemPromptOverride,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAgentConfig = `-- name: UpsertAgentConfig :one
INSERT INTO agent_config (id, model, mode, schedule, system_prompt_override)
VALUES (1, $1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET model = EXCLUDED.model, mode = EXCLUDED.mode, schedule = EXCLUDED.schedule, system_prompt_override = EXCLUDED.system_prompt_override, updated_at = now()
RETURNING id, model, mode, schedule, system_prompt_override, created_at, updated_at
`

type UpsertAgentConfigParams struct {
	Model                string      `json:"model"`
	Mode                 string      `json:"mode"`
	Schedule             pgtype.Text `json:"schedule"`
	SystemPromptOverride pgtype.Text `json:"system_prompt_override"`
}

func (q *Queries) UpsertAgentConfig(ctx context.Context, arg UpsertAgentConfigParams) (AgentConfig, error) {
	row := q.db.QueryRow(ctx, upsertAgentConfig,
		arg.Model,
		arg.Mode,
		arg.Schedule,
		arg.SystemPromptOverride,
	)
	var i AgentConfig
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Mode,
		&i.Schedule,
		&i.SystemPromptOverride,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
