// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_agent_config.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAppAgentConfig = `-- name: GetAppAgentConfig :one
SELECT app_id, model, mode, schedule_interval_secs, system_prompt_override, created_at, updated_at, provider FROM app_agent_config WHERE app_id = $1
`

func (q *Queries) GetAppAgentConfig(ctx context.Context, appID uuid.UUID) (AppAgentConfig, error) {
	row := q.db.QueryRow(ctx, getAppAgentConfig, appID)
	var i AppAgentConfig
	err := row.Scan(
		&i.AppID,
		&i.Model,
		&i.Mode,
		&i.ScheduleIntervalSecs,
		&i.SystemPromptOverride,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
	)
	return i, err
}

const upsertAppAgentConfig = `-- name: UpsertAppAgentConfig :one
INSERT INTO app_agent_config (app_id, model, mode, schedule_interval_secs, system_prompt_override, provider)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (app_id) DO UPDATE
SET model = EXCLUDED.model,
    mode = EXCLUDED.mode,
    schedule_interval_secs = EXCLUDED.schedule_interval_secs,
    system_prompt_override = EXCLUDED.system_prompt_override,
    provider = EXCLUDED.provider,
    updated_at = now()
RETURNING app_id, model, mode, schedule_interval_secs, system_prompt_override, created_at, updated_at, provider
`

type UpsertAppAgentConfigParams struct {
	AppID                uuid.UUID   `json:"app_id"`
	Model                string      `json:"model"`
	Mode                 string      `json:"mode"`
	ScheduleIntervalSecs int32       `json:"schedule_interval_secs"`
	SystemPromptOverride pgtype.Text `json:"system_prompt_override"`
	Provider             string      `json:"provider"`
}

func (q *Queries) UpsertAppAgentConfig(ctx context.Context, arg UpsertAppAgentConfigParams) (AppAgentConfig, error) {
	row := q.db.QueryRow(ctx, upsertAppAgentConfig,
		arg.AppID,
		arg.Model,
		arg.Mode,
		arg.ScheduleIntervalSecs,
		arg.SystemPromptOverride,
		arg.Provider,
	)
	var i AppAgentConfig
	err := row.Scan(
		&i.AppID,
		&i.Model,
		&i.Mode,
		&i.ScheduleIntervalSecs,
		&i.SystemPromptOverride,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
	)
	return i, err
}
