// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countApplicationsByOrg = `-- name: CountApplicationsByOrg :one
SELECT COUNT(*) FROM applications WHERE org_id = $1
`

// Used by the delete-app handler to enforce the "can't delete the last app"
// guard without pulling back every row.
func (q *Queries) CountApplicationsByOrg(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countApplicationsByOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (org_id, name, status)
VALUES ($1, $2, $3)
RETURNING id, org_id, name, status, created_at, updated_at
`

type CreateApplicationParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	Name   string    `json:"name"`
	Status string    `json:"status"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication, arg.OrgID, arg.Name, arg.Status)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteApplication, id)
	return err
}

const getApplication = `-- name: GetApplication :one
SELECT id, org_id, name, status, created_at, updated_at FROM applications WHERE id = $1
`

func (q *Queries) GetApplication(ctx context.Context, id uuid.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationByOrgUser = `-- name: GetApplicationByOrgUser :one
SELECT a.id, a.org_id, a.name, a.status, a.created_at, a.updated_at FROM applications a
JOIN org_members om ON om.org_id = a.org_id
WHERE a.id = $1 AND om.user_id = $2
`

type GetApplicationByOrgUserParams struct {
	AppID  uuid.UUID `json:"app_id"`
	UserID uuid.UUID `json:"user_id"`
}

// Returns the application only if it belongs to an org the given user is a member of.
func (q *Queries) GetApplicationByOrgUser(ctx context.Context, arg GetApplicationByOrgUserParams) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByOrgUser, arg.AppID, arg.UserID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplicationsByOrg = `-- name: ListApplicationsByOrg :many
SELECT id, org_id, name, status, created_at, updated_at FROM applications
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListApplicationsByOrg(ctx context.Context, orgID uuid.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByOrgWithCounts = `-- name: ListApplicationsByOrgWithCounts :many
SELECT
  a.id, a.org_id, a.name, a.status, a.created_at, a.updated_at,
  (SELECT COUNT(*) FROM connections WHERE app_id = a.id) AS connection_count,
  (SELECT COUNT(*) FROM investigation_schedules WHERE app_id = a.id) AS schedule_count
FROM applications a
WHERE a.org_id = $1
ORDER BY a.created_at DESC
`

type ListApplicationsByOrgWithCountsRow struct {
	ID              uuid.UUID `json:"id"`
	OrgID           uuid.UUID `json:"org_id"`
	Name            string    `json:"name"`
	Status          string    `json:"status"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	ConnectionCount int64     `json:"connection_count"`
	ScheduleCount   int64     `json:"schedule_count"`
}

// Same as ListApplicationsByOrg but augments each row with connection/schedule
// counts so the Settings page can render per-app summaries in a single request
// instead of N+1. Subqueries keep the cost linear in #apps — the counts never
// join across connections/schedules rows, so adding more data to either table
// has no multiplicative effect on the query plan.
func (q *Queries) ListApplicationsByOrgWithCounts(ctx context.Context, orgID uuid.UUID) ([]ListApplicationsByOrgWithCountsRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsByOrgWithCounts, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsByOrgWithCountsRow{}
	for rows.Next() {
		var i ListApplicationsByOrgWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConnectionCount,
			&i.ScheduleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications
SET name = $2, status = $3, updated_at = now()
WHERE id = $1
RETURNING id, org_id, name, status, created_at, updated_at
`

type UpdateApplicationParams struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplication, arg.ID, arg.Name, arg.Status)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
