// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: connections.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createConnection = `-- name: CreateConnection :one
INSERT INTO connections (name, type, direction, config, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, type, direction, config, status, last_seen, created_at, updated_at
`

type CreateConnectionParams struct {
	Name      string          `json:"name"`
	Type      string          `json:"type"`
	Direction string          `json:"direction"`
	Config    json.RawMessage `json:"config"`
	Status    string          `json:"status"`
}

func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, createConnection,
		arg.Name,
		arg.Type,
		arg.Direction,
		arg.Config,
		arg.Status,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Direction,
		&i.Config,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConnection = `-- name: DeleteConnection :exec
DELETE FROM connections WHERE id = $1
`

func (q *Queries) DeleteConnection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConnection, id)
	return err
}

const getConnection = `-- name: GetConnection :one
SELECT id, name, type, direction, config, status, last_seen, created_at, updated_at FROM connections WHERE id = $1
`

func (q *Queries) GetConnection(ctx context.Context, id uuid.UUID) (Connection, error) {
	row := q.db.QueryRow(ctx, getConnection, id)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Direction,
		&i.Config,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnections = `-- name: ListConnections :many
SELECT id, name, type, direction, config, status, last_seen, created_at, updated_at FROM connections ORDER BY created_at DESC
`

func (q *Queries) ListConnections(ctx context.Context) ([]Connection, error) {
	rows, err := q.db.Query(ctx, listConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Direction,
			&i.Config,
			&i.Status,
			&i.LastSeen,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnection = `-- name: UpdateConnection :one
UPDATE connections
SET name = $2, type = $3, direction = $4, config = $5, status = $6, updated_at = now()
WHERE id = $1
RETURNING id, name, type, direction, config, status, last_seen, created_at, updated_at
`

type UpdateConnectionParams struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Type      string          `json:"type"`
	Direction string          `json:"direction"`
	Config    json.RawMessage `json:"config"`
	Status    string          `json:"status"`
}

func (q *Queries) UpdateConnection(ctx context.Context, arg UpdateConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, updateConnection,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Direction,
		arg.Config,
		arg.Status,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Direction,
		&i.Config,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConnectionStatus = `-- name: UpdateConnectionStatus :exec
UPDATE connections SET status = $2, last_seen = now(), updated_at = now() WHERE id = $1
`

type UpdateConnectionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateConnectionStatus(ctx context.Context, arg UpdateConnectionStatusParams) error {
	_, err := q.db.Exec(ctx, updateConnectionStatus, arg.ID, arg.Status)
	return err
}
