// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: connections.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createConnection = `-- name: CreateConnection :one
INSERT INTO connections (user_id, app_id, name, type, direction, config, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, type, direction, config, status, last_seen, created_at, updated_at, user_id, app_id
`

type CreateConnectionParams struct {
	UserID    uuid.UUID       `json:"user_id"`
	AppID     uuid.UUID       `json:"app_id"`
	Name      string          `json:"name"`
	Type      string          `json:"type"`
	Direction string          `json:"direction"`
	Config    json.RawMessage `json:"config"`
	Status    string          `json:"status"`
}

func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, createConnection,
		arg.UserID,
		arg.AppID,
		arg.Name,
		arg.Type,
		arg.Direction,
		arg.Config,
		arg.Status,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Direction,
		&i.Config,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.AppID,
	)
	return i, err
}

const deleteConnectionByUser = `-- name: DeleteConnectionByUser :exec
DELETE FROM connections WHERE id = $1 AND user_id = $2
`

type DeleteConnectionByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteConnectionByUser(ctx context.Context, arg DeleteConnectionByUserParams) error {
	_, err := q.db.Exec(ctx, deleteConnectionByUser, arg.ID, arg.UserID)
	return err
}

const getConnectionByUser = `-- name: GetConnectionByUser :one
SELECT id, name, type, direction, config, status, last_seen, created_at, updated_at, user_id, app_id FROM connections WHERE id = $1 AND user_id = $2
`

type GetConnectionByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetConnectionByUser(ctx context.Context, arg GetConnectionByUserParams) (Connection, error) {
	row := q.db.QueryRow(ctx, getConnectionByUser, arg.ID, arg.UserID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Direction,
		&i.Config,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.AppID,
	)
	return i, err
}

const listActiveConnectionsByType = `-- name: ListActiveConnectionsByType :many
SELECT id, name, type, direction, config, status, last_seen, created_at, updated_at, user_id, app_id FROM connections WHERE type = $1 AND status = 'active'
`

func (q *Queries) ListActiveConnectionsByType(ctx context.Context, type_ string) ([]Connection, error) {
	rows, err := q.db.Query(ctx, listActiveConnectionsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Direction,
			&i.Config,
			&i.Status,
			&i.LastSeen,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.AppID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectionsByApp = `-- name: ListConnectionsByApp :many
SELECT id, name, type, direction, config, status, last_seen, created_at, updated_at, user_id, app_id FROM connections WHERE app_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListConnectionsByApp(ctx context.Context, appID uuid.UUID) ([]Connection, error) {
	rows, err := q.db.Query(ctx, listConnectionsByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Direction,
			&i.Config,
			&i.Status,
			&i.LastSeen,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.AppID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectionsByUser = `-- name: ListConnectionsByUser :many
SELECT id, name, type, direction, config, status, last_seen, created_at, updated_at, user_id, app_id FROM connections WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListConnectionsByUser(ctx context.Context, userID uuid.UUID) ([]Connection, error) {
	rows, err := q.db.Query(ctx, listConnectionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Direction,
			&i.Config,
			&i.Status,
			&i.LastSeen,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.AppID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnection = `-- name: UpdateConnection :one
UPDATE connections
SET name = $2, type = $3, direction = $4, config = $5, status = $6, updated_at = now()
WHERE id = $1 AND user_id = $7
RETURNING id, name, type, direction, config, status, last_seen, created_at, updated_at, user_id, app_id
`

type UpdateConnectionParams struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Type      string          `json:"type"`
	Direction string          `json:"direction"`
	Config    json.RawMessage `json:"config"`
	Status    string          `json:"status"`
	UserID    uuid.UUID       `json:"user_id"`
}

func (q *Queries) UpdateConnection(ctx context.Context, arg UpdateConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, updateConnection,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Direction,
		arg.Config,
		arg.Status,
		arg.UserID,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Direction,
		&i.Config,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.AppID,
	)
	return i, err
}

const updateConnectionStatus = `-- name: UpdateConnectionStatus :exec
UPDATE connections SET status = $2, last_seen = now(), updated_at = now() WHERE id = $1
`

type UpdateConnectionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateConnectionStatus(ctx context.Context, arg UpdateConnectionStatusParams) error {
	_, err := q.db.Exec(ctx, updateConnectionStatus, arg.ID, arg.Status)
	return err
}
