// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (investigation_id, title, messages)
VALUES ($1, $2, $3)
RETURNING id, investigation_id, title, messages, created_at, updated_at
`

type CreateConversationParams struct {
	InvestigationID pgtype.UUID     `json:"investigation_id"`
	Title           pgtype.Text     `json:"title"`
	Messages        json.RawMessage `json:"messages"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.InvestigationID, arg.Title, arg.Messages)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.InvestigationID,
		&i.Title,
		&i.Messages,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, investigation_id, title, messages, created_at, updated_at FROM conversations WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.InvestigationID,
		&i.Title,
		&i.Messages,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, investigation_id, title, messages, created_at, updated_at FROM conversations ORDER BY created_at DESC
`

func (q *Queries) ListConversations(ctx context.Context) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.InvestigationID,
			&i.Title,
			&i.Messages,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationMessages = `-- name: UpdateConversationMessages :exec
UPDATE conversations SET messages = $2, updated_at = now() WHERE id = $1
`

type UpdateConversationMessagesParams struct {
	ID       uuid.UUID       `json:"id"`
	Messages json.RawMessage `json:"messages"`
}

func (q *Queries) UpdateConversationMessages(ctx context.Context, arg UpdateConversationMessagesParams) error {
	_, err := q.db.Exec(ctx, updateConversationMessages, arg.ID, arg.Messages)
	return err
}
