// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (user_id, investigation_id, title, messages)
VALUES ($1, $2, $3, $4)
RETURNING id, investigation_id, title, messages, created_at, updated_at, user_id
`

type CreateConversationParams struct {
	UserID          uuid.UUID       `json:"user_id"`
	InvestigationID *uuid.UUID      `json:"investigation_id"`
	Title           pgtype.Text     `json:"title"`
	Messages        json.RawMessage `json:"messages"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.UserID,
		arg.InvestigationID,
		arg.Title,
		arg.Messages,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.InvestigationID,
		&i.Title,
		&i.Messages,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getConversationByUser = `-- name: GetConversationByUser :one
SELECT id, investigation_id, title, messages, created_at, updated_at, user_id FROM conversations WHERE id = $1 AND user_id = $2
`

type GetConversationByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetConversationByUser(ctx context.Context, arg GetConversationByUserParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByUser, arg.ID, arg.UserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.InvestigationID,
		&i.Title,
		&i.Messages,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const listConversationsByUser = `-- name: ListConversationsByUser :many
SELECT id, investigation_id, title, messages, created_at, updated_at, user_id FROM conversations
WHERE user_id = $1
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

type ListConversationsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListConversationsByUser(ctx context.Context, arg ListConversationsByUserParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.InvestigationID,
			&i.Title,
			&i.Messages,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationMessagesByUser = `-- name: UpdateConversationMessagesByUser :exec
UPDATE conversations SET messages = $2, updated_at = now()
WHERE id = $1 AND user_id = $3
`

type UpdateConversationMessagesByUserParams struct {
	ID       uuid.UUID       `json:"id"`
	Messages json.RawMessage `json:"messages"`
	UserID   uuid.UUID       `json:"user_id"`
}

func (q *Queries) UpdateConversationMessagesByUser(ctx context.Context, arg UpdateConversationMessagesByUserParams) error {
	_, err := q.db.Exec(ctx, updateConversationMessagesByUser, arg.ID, arg.Messages, arg.UserID)
	return err
}

const updateConversationTitleByUser = `-- name: UpdateConversationTitleByUser :exec
UPDATE conversations SET title = $2, updated_at = now()
WHERE id = $1 AND user_id = $3
`

type UpdateConversationTitleByUserParams struct {
	ID     uuid.UUID   `json:"id"`
	Title  pgtype.Text `json:"title"`
	UserID uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateConversationTitleByUser(ctx context.Context, arg UpdateConversationTitleByUserParams) error {
	_, err := q.db.Exec(ctx, updateConversationTitleByUser, arg.ID, arg.Title, arg.UserID)
	return err
}
