// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github_repos.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteGitHubRepo = `-- name: DeleteGitHubRepo :exec
DELETE FROM github_repos WHERE id = $1
`

func (q *Queries) DeleteGitHubRepo(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGitHubRepo, id)
	return err
}

const listEnabledGitHubReposByApp = `-- name: ListEnabledGitHubReposByApp :many
SELECT gr.id, gr.connection_id, gr.repo_full_name, gr.repo_id, gr.default_branch, gr.enabled, gr.created_at,
       c.config AS connection_config
FROM github_repos gr
JOIN connections c ON c.id = gr.connection_id
WHERE c.app_id = $1
  AND c.type = 'github'
  AND c.status = 'active'
  AND gr.enabled = true
ORDER BY gr.repo_full_name
`

type ListEnabledGitHubReposByAppRow struct {
	ID               uuid.UUID       `json:"id"`
	ConnectionID     uuid.UUID       `json:"connection_id"`
	RepoFullName     string          `json:"repo_full_name"`
	RepoID           int64           `json:"repo_id"`
	DefaultBranch    string          `json:"default_branch"`
	Enabled          bool            `json:"enabled"`
	CreatedAt        time.Time       `json:"created_at"`
	ConnectionConfig json.RawMessage `json:"connection_config"`
}

func (q *Queries) ListEnabledGitHubReposByApp(ctx context.Context, appID uuid.UUID) ([]ListEnabledGitHubReposByAppRow, error) {
	rows, err := q.db.Query(ctx, listEnabledGitHubReposByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledGitHubReposByAppRow{}
	for rows.Next() {
		var i ListEnabledGitHubReposByAppRow
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.RepoFullName,
			&i.RepoID,
			&i.DefaultBranch,
			&i.Enabled,
			&i.CreatedAt,
			&i.ConnectionConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitHubReposByConnection = `-- name: ListGitHubReposByConnection :many
SELECT id, connection_id, repo_full_name, repo_id, default_branch, enabled, created_at
FROM github_repos
WHERE connection_id = $1
ORDER BY repo_full_name
`

func (q *Queries) ListGitHubReposByConnection(ctx context.Context, connectionID uuid.UUID) ([]GithubRepo, error) {
	rows, err := q.db.Query(ctx, listGitHubReposByConnection, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubRepo{}
	for rows.Next() {
		var i GithubRepo
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.RepoFullName,
			&i.RepoID,
			&i.DefaultBranch,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGitHubRepo = `-- name: UpsertGitHubRepo :one
INSERT INTO github_repos (connection_id, repo_full_name, repo_id, default_branch, enabled)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (connection_id, repo_id)
DO UPDATE SET
    repo_full_name = EXCLUDED.repo_full_name,
    default_branch = EXCLUDED.default_branch,
    enabled = EXCLUDED.enabled
RETURNING id, connection_id, repo_full_name, repo_id, default_branch, enabled, created_at
`

type UpsertGitHubRepoParams struct {
	ConnectionID  uuid.UUID `json:"connection_id"`
	RepoFullName  string    `json:"repo_full_name"`
	RepoID        int64     `json:"repo_id"`
	DefaultBranch string    `json:"default_branch"`
	Enabled       bool      `json:"enabled"`
}

func (q *Queries) UpsertGitHubRepo(ctx context.Context, arg UpsertGitHubRepoParams) (GithubRepo, error) {
	row := q.db.QueryRow(ctx, upsertGitHubRepo,
		arg.ConnectionID,
		arg.RepoFullName,
		arg.RepoID,
		arg.DefaultBranch,
		arg.Enabled,
	)
	var i GithubRepo
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.RepoFullName,
		&i.RepoID,
		&i.DefaultBranch,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}
