// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: investigation_schedules.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO investigation_schedules (app_id, name, prompt, interval_secs, cron_expr, enabled)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, app_id, name, prompt, interval_secs, cron_expr, enabled, last_run_at, last_status, last_error, last_summary, created_at, updated_at
`

type CreateScheduleParams struct {
	AppID        uuid.UUID   `json:"app_id"`
	Name         string      `json:"name"`
	Prompt       string      `json:"prompt"`
	IntervalSecs int32       `json:"interval_secs"`
	CronExpr     pgtype.Text `json:"cron_expr"`
	Enabled      bool        `json:"enabled"`
}

// cron_expr is nullable: schedules created via the simple interval preset
// store NULL here and rely on interval_secs. Schedules created via cron_expr
// store 0 for interval_secs (unused; shouldFire prefers cron when set).
func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (InvestigationSchedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.AppID,
		arg.Name,
		arg.Prompt,
		arg.IntervalSecs,
		arg.CronExpr,
		arg.Enabled,
	)
	var i InvestigationSchedule
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.Prompt,
		&i.IntervalSecs,
		&i.CronExpr,
		&i.Enabled,
		&i.LastRunAt,
		&i.LastStatus,
		&i.LastError,
		&i.LastSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM investigation_schedules WHERE id = $1
`

func (q *Queries) DeleteSchedule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSchedule, id)
	return err
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, app_id, name, prompt, interval_secs, cron_expr, enabled, last_run_at, last_status, last_error, last_summary, created_at, updated_at FROM investigation_schedules
WHERE id = $1
`

func (q *Queries) GetSchedule(ctx context.Context, id uuid.UUID) (InvestigationSchedule, error) {
	row := q.db.QueryRow(ctx, getSchedule, id)
	var i InvestigationSchedule
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.Prompt,
		&i.IntervalSecs,
		&i.CronExpr,
		&i.Enabled,
		&i.LastRunAt,
		&i.LastStatus,
		&i.LastError,
		&i.LastSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledSchedules = `-- name: ListEnabledSchedules :many
SELECT id, app_id, name, prompt, interval_secs, cron_expr, enabled, last_run_at, last_status, last_error, last_summary, created_at, updated_at FROM investigation_schedules
WHERE enabled = true
ORDER BY last_run_at ASC NULLS FIRST
`

// Used by the scheduler loop on each tick. Ordered so never-run schedules
// (NULL last_run_at) fire first, then oldest-last-run first.
func (q *Queries) ListEnabledSchedules(ctx context.Context) ([]InvestigationSchedule, error) {
	rows, err := q.db.Query(ctx, listEnabledSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvestigationSchedule{}
	for rows.Next() {
		var i InvestigationSchedule
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Name,
			&i.Prompt,
			&i.IntervalSecs,
			&i.CronExpr,
			&i.Enabled,
			&i.LastRunAt,
			&i.LastStatus,
			&i.LastError,
			&i.LastSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesByApp = `-- name: ListSchedulesByApp :many
SELECT id, app_id, name, prompt, interval_secs, cron_expr, enabled, last_run_at, last_status, last_error, last_summary, created_at, updated_at FROM investigation_schedules
WHERE app_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSchedulesByApp(ctx context.Context, appID uuid.UUID) ([]InvestigationSchedule, error) {
	rows, err := q.db.Query(ctx, listSchedulesByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvestigationSchedule{}
	for rows.Next() {
		var i InvestigationSchedule
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Name,
			&i.Prompt,
			&i.IntervalSecs,
			&i.CronExpr,
			&i.Enabled,
			&i.LastRunAt,
			&i.LastStatus,
			&i.LastError,
			&i.LastSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markScheduleRun = `-- name: MarkScheduleRun :exec
UPDATE investigation_schedules
SET last_run_at  = now(),
    last_status  = $2,
    last_error   = $3,
    last_summary = $4,
    updated_at   = now()
WHERE id = $1
`

type MarkScheduleRunParams struct {
	ID          uuid.UUID   `json:"id"`
	LastStatus  pgtype.Text `json:"last_status"`
	LastError   pgtype.Text `json:"last_error"`
	LastSummary pgtype.Text `json:"last_summary"`
}

// Called by the scheduler after every run (success or error) to advance
// last_run_at and record the outcome. Takes nullable status/error/summary
// so both the success and error paths share a single query.
func (q *Queries) MarkScheduleRun(ctx context.Context, arg MarkScheduleRunParams) error {
	_, err := q.db.Exec(ctx, markScheduleRun,
		arg.ID,
		arg.LastStatus,
		arg.LastError,
		arg.LastSummary,
	)
	return err
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE investigation_schedules
SET name = $2,
    prompt = $3,
    interval_secs = $4,
    cron_expr = $5,
    enabled = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, app_id, name, prompt, interval_secs, cron_expr, enabled, last_run_at, last_status, last_error, last_summary, created_at, updated_at
`

type UpdateScheduleParams struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	Prompt       string      `json:"prompt"`
	IntervalSecs int32       `json:"interval_secs"`
	CronExpr     pgtype.Text `json:"cron_expr"`
	Enabled      bool        `json:"enabled"`
}

// PATCH-style update that overwrites all four scheduling fields; the handler
// is responsible for enforcing "exactly one of interval_secs / cron_expr".
func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (InvestigationSchedule, error) {
	row := q.db.QueryRow(ctx, updateSchedule,
		arg.ID,
		arg.Name,
		arg.Prompt,
		arg.IntervalSecs,
		arg.CronExpr,
		arg.Enabled,
	)
	var i InvestigationSchedule
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.Prompt,
		&i.IntervalSecs,
		&i.CronExpr,
		&i.Enabled,
		&i.LastRunAt,
		&i.LastStatus,
		&i.LastError,
		&i.LastSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
