// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: investigations.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvestigation = `-- name: CreateInvestigation :one
INSERT INTO investigations (
    trigger_type, trigger_source, summary, severity, status, context
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, trigger_type, trigger_source, summary, severity, status, context, findings, tool_trace, resolution, started_at, resolved_at
`

type CreateInvestigationParams struct {
	TriggerType   string          `json:"trigger_type"`
	TriggerSource pgtype.Text     `json:"trigger_source"`
	Summary       string          `json:"summary"`
	Severity      string          `json:"severity"`
	Status        string          `json:"status"`
	Context       json.RawMessage `json:"context"`
}

func (q *Queries) CreateInvestigation(ctx context.Context, arg CreateInvestigationParams) (Investigation, error) {
	row := q.db.QueryRow(ctx, createInvestigation,
		arg.TriggerType,
		arg.TriggerSource,
		arg.Summary,
		arg.Severity,
		arg.Status,
		arg.Context,
	)
	var i Investigation
	err := row.Scan(
		&i.ID,
		&i.TriggerType,
		&i.TriggerSource,
		&i.Summary,
		&i.Severity,
		&i.Status,
		&i.Context,
		&i.Findings,
		&i.ToolTrace,
		&i.Resolution,
		&i.StartedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const dismissInvestigation = `-- name: DismissInvestigation :exec
UPDATE investigations
SET status = 'dismissed', resolution = $2
WHERE id = $1
`

type DismissInvestigationParams struct {
	ID         uuid.UUID   `json:"id"`
	Resolution pgtype.Text `json:"resolution"`
}

func (q *Queries) DismissInvestigation(ctx context.Context, arg DismissInvestigationParams) error {
	_, err := q.db.Exec(ctx, dismissInvestigation, arg.ID, arg.Resolution)
	return err
}

const getInvestigation = `-- name: GetInvestigation :one
SELECT id, trigger_type, trigger_source, summary, severity, status, context, findings, tool_trace, resolution, started_at, resolved_at FROM investigations WHERE id = $1
`

func (q *Queries) GetInvestigation(ctx context.Context, id uuid.UUID) (Investigation, error) {
	row := q.db.QueryRow(ctx, getInvestigation, id)
	var i Investigation
	err := row.Scan(
		&i.ID,
		&i.TriggerType,
		&i.TriggerSource,
		&i.Summary,
		&i.Severity,
		&i.Status,
		&i.Context,
		&i.Findings,
		&i.ToolTrace,
		&i.Resolution,
		&i.StartedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listInvestigationsByDateRange = `-- name: ListInvestigationsByDateRange :many
SELECT id, trigger_type, trigger_source, summary, severity, status, context, findings, tool_trace, resolution, started_at, resolved_at FROM investigations
WHERE started_at >= $1 AND started_at <= $2
ORDER BY started_at DESC
`

type ListInvestigationsByDateRangeParams struct {
	StartedAt   time.Time `json:"started_at"`
	StartedAt_2 time.Time `json:"started_at_2"`
}

func (q *Queries) ListInvestigationsByDateRange(ctx context.Context, arg ListInvestigationsByDateRangeParams) ([]Investigation, error) {
	rows, err := q.db.Query(ctx, listInvestigationsByDateRange, arg.StartedAt, arg.StartedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Investigation{}
	for rows.Next() {
		var i Investigation
		if err := rows.Scan(
			&i.ID,
			&i.TriggerType,
			&i.TriggerSource,
			&i.Summary,
			&i.Severity,
			&i.Status,
			&i.Context,
			&i.Findings,
			&i.ToolTrace,
			&i.Resolution,
			&i.StartedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenInvestigations = `-- name: ListOpenInvestigations :many
SELECT id, trigger_type, trigger_source, summary, severity, status, context, findings, tool_trace, resolution, started_at, resolved_at FROM investigations
WHERE status IN ('open', 'investigating')
ORDER BY started_at DESC
`

func (q *Queries) ListOpenInvestigations(ctx context.Context) ([]Investigation, error) {
	rows, err := q.db.Query(ctx, listOpenInvestigations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Investigation{}
	for rows.Next() {
		var i Investigation
		if err := rows.Scan(
			&i.ID,
			&i.TriggerType,
			&i.TriggerSource,
			&i.Summary,
			&i.Severity,
			&i.Status,
			&i.Context,
			&i.Findings,
			&i.ToolTrace,
			&i.Resolution,
			&i.StartedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveInvestigation = `-- name: ResolveInvestigation :exec
UPDATE investigations
SET status = 'resolved', resolution = $2, resolved_at = now()
WHERE id = $1
`

type ResolveInvestigationParams struct {
	ID         uuid.UUID   `json:"id"`
	Resolution pgtype.Text `json:"resolution"`
}

func (q *Queries) ResolveInvestigation(ctx context.Context, arg ResolveInvestigationParams) error {
	_, err := q.db.Exec(ctx, resolveInvestigation, arg.ID, arg.Resolution)
	return err
}

const updateInvestigationFindings = `-- name: UpdateInvestigationFindings :exec
UPDATE investigations
SET findings = $2, tool_trace = $3, status = $4, resolved_at = $5
WHERE id = $1
`

type UpdateInvestigationFindingsParams struct {
	ID         uuid.UUID  `json:"id"`
	Findings   []byte     `json:"findings"`
	ToolTrace  []byte     `json:"tool_trace"`
	Status     string     `json:"status"`
	ResolvedAt *time.Time `json:"resolved_at"`
}

func (q *Queries) UpdateInvestigationFindings(ctx context.Context, arg UpdateInvestigationFindingsParams) error {
	_, err := q.db.Exec(ctx, updateInvestigationFindings,
		arg.ID,
		arg.Findings,
		arg.ToolTrace,
		arg.Status,
		arg.ResolvedAt,
	)
	return err
}
