// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: log_buffer.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countLogsByApp = `-- name: CountLogsByApp :one
SELECT count(*) FROM log_buffer
WHERE user_id = $1 AND app_id = $2
`

type CountLogsByAppParams struct {
	UserID uuid.UUID   `json:"user_id"`
	AppID  pgtype.UUID `json:"app_id"`
}

func (q *Queries) CountLogsByApp(ctx context.Context, arg CountLogsByAppParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLogsByApp, arg.UserID, arg.AppID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLogsByAppAndSeverity = `-- name: CountLogsByAppAndSeverity :one
SELECT count(*) FROM log_buffer
WHERE user_id = $1 AND app_id = $2 AND severity = $3
`

type CountLogsByAppAndSeverityParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	AppID    pgtype.UUID `json:"app_id"`
	Severity pgtype.Text `json:"severity"`
}

func (q *Queries) CountLogsByAppAndSeverity(ctx context.Context, arg CountLogsByAppAndSeverityParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLogsByAppAndSeverity, arg.UserID, arg.AppID, arg.Severity)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLogsByUser = `-- name: CountLogsByUser :one
SELECT count(*) FROM log_buffer
WHERE user_id = $1
`

func (q *Queries) CountLogsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLogsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLogsByUserAndConnection = `-- name: CountLogsByUserAndConnection :one
SELECT count(*) FROM log_buffer
WHERE user_id = $1 AND connection_id = $2
`

type CountLogsByUserAndConnectionParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ConnectionID uuid.UUID `json:"connection_id"`
}

func (q *Queries) CountLogsByUserAndConnection(ctx context.Context, arg CountLogsByUserAndConnectionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLogsByUserAndConnection, arg.UserID, arg.ConnectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLogsByUserAndSeverity = `-- name: CountLogsByUserAndSeverity :one
SELECT count(*) FROM log_buffer
WHERE user_id = $1 AND severity = $2
`

type CountLogsByUserAndSeverityParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	Severity pgtype.Text `json:"severity"`
}

func (q *Queries) CountLogsByUserAndSeverity(ctx context.Context, arg CountLogsByUserAndSeverityParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLogsByUserAndSeverity, arg.UserID, arg.Severity)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getConnectionByWebhookToken = `-- name: GetConnectionByWebhookToken :one
SELECT id, name, type, direction, config, status, last_seen, created_at, updated_at, user_id, app_id FROM connections
WHERE config->>'webhook_token' = $1::text AND type = 'webhook_logs' AND status = 'active'
`

func (q *Queries) GetConnectionByWebhookToken(ctx context.Context, webhookToken string) (Connection, error) {
	row := q.db.QueryRow(ctx, getConnectionByWebhookToken, webhookToken)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Direction,
		&i.Config,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.AppID,
	)
	return i, err
}

const insertLogEntry = `-- name: InsertLogEntry :one
INSERT INTO log_buffer (connection_id, source_type, severity, payload, user_id, app_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, connection_id, source_type, severity, payload, ingested_at, user_id, app_id
`

type InsertLogEntryParams struct {
	ConnectionID uuid.UUID       `json:"connection_id"`
	SourceType   string          `json:"source_type"`
	Severity     pgtype.Text     `json:"severity"`
	Payload      json.RawMessage `json:"payload"`
	UserID       uuid.UUID       `json:"user_id"`
	AppID        pgtype.UUID     `json:"app_id"`
}

func (q *Queries) InsertLogEntry(ctx context.Context, arg InsertLogEntryParams) (LogBuffer, error) {
	row := q.db.QueryRow(ctx, insertLogEntry,
		arg.ConnectionID,
		arg.SourceType,
		arg.Severity,
		arg.Payload,
		arg.UserID,
		arg.AppID,
	)
	var i LogBuffer
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.SourceType,
		&i.Severity,
		&i.Payload,
		&i.IngestedAt,
		&i.UserID,
		&i.AppID,
	)
	return i, err
}

const listLogsByApp = `-- name: ListLogsByApp :many
SELECT id, connection_id, source_type, severity, payload, ingested_at, user_id, app_id FROM log_buffer
WHERE user_id = $1 AND app_id = $2
ORDER BY ingested_at DESC
LIMIT $3 OFFSET $4
`

type ListLogsByAppParams struct {
	UserID uuid.UUID   `json:"user_id"`
	AppID  pgtype.UUID `json:"app_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListLogsByApp(ctx context.Context, arg ListLogsByAppParams) ([]LogBuffer, error) {
	rows, err := q.db.Query(ctx, listLogsByApp,
		arg.UserID,
		arg.AppID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogBuffer{}
	for rows.Next() {
		var i LogBuffer
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.SourceType,
			&i.Severity,
			&i.Payload,
			&i.IngestedAt,
			&i.UserID,
			&i.AppID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogsByAppAndSeverity = `-- name: ListLogsByAppAndSeverity :many
SELECT id, connection_id, source_type, severity, payload, ingested_at, user_id, app_id FROM log_buffer
WHERE user_id = $1 AND app_id = $2 AND severity = $3
ORDER BY ingested_at DESC
LIMIT $4 OFFSET $5
`

type ListLogsByAppAndSeverityParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	AppID    pgtype.UUID `json:"app_id"`
	Severity pgtype.Text `json:"severity"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListLogsByAppAndSeverity(ctx context.Context, arg ListLogsByAppAndSeverityParams) ([]LogBuffer, error) {
	rows, err := q.db.Query(ctx, listLogsByAppAndSeverity,
		arg.UserID,
		arg.AppID,
		arg.Severity,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogBuffer{}
	for rows.Next() {
		var i LogBuffer
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.SourceType,
			&i.Severity,
			&i.Payload,
			&i.IngestedAt,
			&i.UserID,
			&i.AppID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogsByUser = `-- name: ListLogsByUser :many
SELECT id, connection_id, source_type, severity, payload, ingested_at, user_id, app_id FROM log_buffer
WHERE user_id = $1
ORDER BY ingested_at DESC
LIMIT $2 OFFSET $3
`

type ListLogsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListLogsByUser(ctx context.Context, arg ListLogsByUserParams) ([]LogBuffer, error) {
	rows, err := q.db.Query(ctx, listLogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogBuffer{}
	for rows.Next() {
		var i LogBuffer
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.SourceType,
			&i.Severity,
			&i.Payload,
			&i.IngestedAt,
			&i.UserID,
			&i.AppID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogsByUserAndConnection = `-- name: ListLogsByUserAndConnection :many
SELECT id, connection_id, source_type, severity, payload, ingested_at, user_id, app_id FROM log_buffer
WHERE user_id = $1 AND connection_id = $2
ORDER BY ingested_at DESC
LIMIT $3 OFFSET $4
`

type ListLogsByUserAndConnectionParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ConnectionID uuid.UUID `json:"connection_id"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

func (q *Queries) ListLogsByUserAndConnection(ctx context.Context, arg ListLogsByUserAndConnectionParams) ([]LogBuffer, error) {
	rows, err := q.db.Query(ctx, listLogsByUserAndConnection,
		arg.UserID,
		arg.ConnectionID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogBuffer{}
	for rows.Next() {
		var i LogBuffer
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.SourceType,
			&i.Severity,
			&i.Payload,
			&i.IngestedAt,
			&i.UserID,
			&i.AppID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogsByUserAndSeverity = `-- name: ListLogsByUserAndSeverity :many
SELECT id, connection_id, source_type, severity, payload, ingested_at, user_id, app_id FROM log_buffer
WHERE user_id = $1 AND severity = $2
ORDER BY ingested_at DESC
LIMIT $3 OFFSET $4
`

type ListLogsByUserAndSeverityParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	Severity pgtype.Text `json:"severity"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListLogsByUserAndSeverity(ctx context.Context, arg ListLogsByUserAndSeverityParams) ([]LogBuffer, error) {
	rows, err := q.db.Query(ctx, listLogsByUserAndSeverity,
		arg.UserID,
		arg.Severity,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogBuffer{}
	for rows.Next() {
		var i LogBuffer
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.SourceType,
			&i.Severity,
			&i.Payload,
			&i.IngestedAt,
			&i.UserID,
			&i.AppID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneExpiredLogs = `-- name: PruneExpiredLogs :execrows
DELETE FROM log_buffer WHERE ingested_at < now() - interval '48 hours'
`

func (q *Queries) PruneExpiredLogs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneExpiredLogs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchLogsByUser = `-- name: SearchLogsByUser :many
SELECT id, connection_id, source_type, severity, payload, ingested_at, user_id, app_id FROM log_buffer
WHERE user_id = $1 AND payload::text ILIKE '%' || $2::text || '%' ESCAPE '\'
ORDER BY ingested_at DESC
LIMIT $4 OFFSET $3
`

type SearchLogsByUserParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Query     string    `json:"query"`
	RowOffset int32     `json:"row_offset"`
	RowLimit  int32     `json:"row_limit"`
}

func (q *Queries) SearchLogsByUser(ctx context.Context, arg SearchLogsByUserParams) ([]LogBuffer, error) {
	rows, err := q.db.Query(ctx, searchLogsByUser,
		arg.UserID,
		arg.Query,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogBuffer{}
	for rows.Next() {
		var i LogBuffer
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.SourceType,
			&i.Severity,
			&i.Payload,
			&i.IngestedAt,
			&i.UserID,
			&i.AppID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLogsByUserAndSeverity = `-- name: SearchLogsByUserAndSeverity :many
SELECT id, connection_id, source_type, severity, payload, ingested_at, user_id, app_id FROM log_buffer
WHERE user_id = $1 AND payload::text ILIKE '%' || $2::text || '%' ESCAPE '\' AND severity = $3
ORDER BY ingested_at DESC
LIMIT $5 OFFSET $4
`

type SearchLogsByUserAndSeverityParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	Query     string      `json:"query"`
	Severity  pgtype.Text `json:"severity"`
	RowOffset int32       `json:"row_offset"`
	RowLimit  int32       `json:"row_limit"`
}

func (q *Queries) SearchLogsByUserAndSeverity(ctx context.Context, arg SearchLogsByUserAndSeverityParams) ([]LogBuffer, error) {
	rows, err := q.db.Query(ctx, searchLogsByUserAndSeverity,
		arg.UserID,
		arg.Query,
		arg.Severity,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogBuffer{}
	for rows.Next() {
		var i LogBuffer
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.SourceType,
			&i.Severity,
			&i.Payload,
			&i.IngestedAt,
			&i.UserID,
			&i.AppID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
