// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: log_buffer.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertLogEntry = `-- name: InsertLogEntry :exec
INSERT INTO log_buffer (connection_id, source_type, severity, payload)
VALUES ($1, $2, $3, $4)
`

type InsertLogEntryParams struct {
	ConnectionID uuid.UUID       `json:"connection_id"`
	SourceType   string          `json:"source_type"`
	Severity     pgtype.Text     `json:"severity"`
	Payload      json.RawMessage `json:"payload"`
}

func (q *Queries) InsertLogEntry(ctx context.Context, arg InsertLogEntryParams) error {
	_, err := q.db.Exec(ctx, insertLogEntry,
		arg.ConnectionID,
		arg.SourceType,
		arg.Severity,
		arg.Payload,
	)
	return err
}

const listLogsByConnection = `-- name: ListLogsByConnection :many
SELECT id, connection_id, source_type, severity, payload, ingested_at FROM log_buffer
WHERE connection_id = $1 AND ingested_at > now() - interval '1 hour'
ORDER BY ingested_at DESC
`

func (q *Queries) ListLogsByConnection(ctx context.Context, connectionID uuid.UUID) ([]LogBuffer, error) {
	rows, err := q.db.Query(ctx, listLogsByConnection, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogBuffer{}
	for rows.Next() {
		var i LogBuffer
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.SourceType,
			&i.Severity,
			&i.Payload,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogsBySeverity = `-- name: ListLogsBySeverity :many
SELECT id, connection_id, source_type, severity, payload, ingested_at FROM log_buffer
WHERE severity = $1 AND ingested_at > now() - interval '1 hour'
ORDER BY ingested_at DESC
`

func (q *Queries) ListLogsBySeverity(ctx context.Context, severity pgtype.Text) ([]LogBuffer, error) {
	rows, err := q.db.Query(ctx, listLogsBySeverity, severity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogBuffer{}
	for rows.Next() {
		var i LogBuffer
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.SourceType,
			&i.Severity,
			&i.Payload,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentLogs = `-- name: ListRecentLogs :many
SELECT id, connection_id, source_type, severity, payload, ingested_at FROM log_buffer
WHERE ingested_at > now() - interval '1 hour'
ORDER BY ingested_at DESC
`

func (q *Queries) ListRecentLogs(ctx context.Context) ([]LogBuffer, error) {
	rows, err := q.db.Query(ctx, listRecentLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogBuffer{}
	for rows.Next() {
		var i LogBuffer
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.SourceType,
			&i.Severity,
			&i.Payload,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneExpiredLogs = `-- name: PruneExpiredLogs :execrows
DELETE FROM log_buffer WHERE ingested_at < now() - interval '24 hours'
`

func (q *Queries) PruneExpiredLogs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneExpiredLogs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
