// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: log_buffer.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countLogsByUser = `-- name: CountLogsByUser :one
SELECT count(*) FROM log_buffer lb
JOIN connections c ON c.id = lb.connection_id
WHERE c.user_id = $1
`

func (q *Queries) CountLogsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLogsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getConnectionByWebhookToken = `-- name: GetConnectionByWebhookToken :one
SELECT id, name, type, direction, config, status, last_seen, created_at, updated_at, user_id FROM connections
WHERE config->>'webhook_token' = $1::text AND type = 'webhook_logs' AND status = 'active'
`

func (q *Queries) GetConnectionByWebhookToken(ctx context.Context, webhookToken string) (Connection, error) {
	row := q.db.QueryRow(ctx, getConnectionByWebhookToken, webhookToken)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Direction,
		&i.Config,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const insertLogEntry = `-- name: InsertLogEntry :one
INSERT INTO log_buffer (connection_id, source_type, severity, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, connection_id, source_type, severity, payload, ingested_at
`

type InsertLogEntryParams struct {
	ConnectionID uuid.UUID       `json:"connection_id"`
	SourceType   string          `json:"source_type"`
	Severity     pgtype.Text     `json:"severity"`
	Payload      json.RawMessage `json:"payload"`
}

func (q *Queries) InsertLogEntry(ctx context.Context, arg InsertLogEntryParams) (LogBuffer, error) {
	row := q.db.QueryRow(ctx, insertLogEntry,
		arg.ConnectionID,
		arg.SourceType,
		arg.Severity,
		arg.Payload,
	)
	var i LogBuffer
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.SourceType,
		&i.Severity,
		&i.Payload,
		&i.IngestedAt,
	)
	return i, err
}

const listLogsByUser = `-- name: ListLogsByUser :many
SELECT lb.id, lb.connection_id, lb.source_type, lb.severity, lb.payload, lb.ingested_at FROM log_buffer lb
JOIN connections c ON c.id = lb.connection_id
WHERE c.user_id = $1
ORDER BY lb.ingested_at DESC
LIMIT $2 OFFSET $3
`

type ListLogsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListLogsByUser(ctx context.Context, arg ListLogsByUserParams) ([]LogBuffer, error) {
	rows, err := q.db.Query(ctx, listLogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogBuffer{}
	for rows.Next() {
		var i LogBuffer
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.SourceType,
			&i.Severity,
			&i.Payload,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogsByUserAndConnection = `-- name: ListLogsByUserAndConnection :many
SELECT lb.id, lb.connection_id, lb.source_type, lb.severity, lb.payload, lb.ingested_at FROM log_buffer lb
JOIN connections c ON c.id = lb.connection_id
WHERE c.user_id = $1 AND lb.connection_id = $2
ORDER BY lb.ingested_at DESC
LIMIT $3 OFFSET $4
`

type ListLogsByUserAndConnectionParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ConnectionID uuid.UUID `json:"connection_id"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

func (q *Queries) ListLogsByUserAndConnection(ctx context.Context, arg ListLogsByUserAndConnectionParams) ([]LogBuffer, error) {
	rows, err := q.db.Query(ctx, listLogsByUserAndConnection,
		arg.UserID,
		arg.ConnectionID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogBuffer{}
	for rows.Next() {
		var i LogBuffer
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.SourceType,
			&i.Severity,
			&i.Payload,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogsByUserAndSeverity = `-- name: ListLogsByUserAndSeverity :many
SELECT lb.id, lb.connection_id, lb.source_type, lb.severity, lb.payload, lb.ingested_at FROM log_buffer lb
JOIN connections c ON c.id = lb.connection_id
WHERE c.user_id = $1 AND lb.severity = $2
ORDER BY lb.ingested_at DESC
LIMIT $3 OFFSET $4
`

type ListLogsByUserAndSeverityParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	Severity pgtype.Text `json:"severity"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListLogsByUserAndSeverity(ctx context.Context, arg ListLogsByUserAndSeverityParams) ([]LogBuffer, error) {
	rows, err := q.db.Query(ctx, listLogsByUserAndSeverity,
		arg.UserID,
		arg.Severity,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogBuffer{}
	for rows.Next() {
		var i LogBuffer
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.SourceType,
			&i.Severity,
			&i.Payload,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneExpiredLogs = `-- name: PruneExpiredLogs :execrows
DELETE FROM log_buffer WHERE ingested_at < now() - interval '24 hours'
`

func (q *Queries) PruneExpiredLogs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneExpiredLogs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
