// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentConfig struct {
	ID                   int32       `json:"id"`
	Model                string      `json:"model"`
	Mode                 string      `json:"mode"`
	Schedule             pgtype.Text `json:"schedule"`
	SystemPromptOverride pgtype.Text `json:"system_prompt_override"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
}

type Connection struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Type      string          `json:"type"`
	Direction string          `json:"direction"`
	Config    json.RawMessage `json:"config"`
	Status    string          `json:"status"`
	LastSeen  *time.Time      `json:"last_seen"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type Conversation struct {
	ID              uuid.UUID       `json:"id"`
	InvestigationID pgtype.UUID     `json:"investigation_id"`
	Title           pgtype.Text     `json:"title"`
	Messages        json.RawMessage `json:"messages"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type Investigation struct {
	ID            uuid.UUID       `json:"id"`
	TriggerType   string          `json:"trigger_type"`
	TriggerSource pgtype.Text     `json:"trigger_source"`
	Summary       string          `json:"summary"`
	Severity      string          `json:"severity"`
	Status        string          `json:"status"`
	Context       json.RawMessage `json:"context"`
	Findings      []byte          `json:"findings"`
	ToolTrace     []byte          `json:"tool_trace"`
	Resolution    pgtype.Text     `json:"resolution"`
	StartedAt     time.Time       `json:"started_at"`
	ResolvedAt    *time.Time      `json:"resolved_at"`
}

type LogBuffer struct {
	ID           uuid.UUID       `json:"id"`
	ConnectionID uuid.UUID       `json:"connection_id"`
	SourceType   string          `json:"source_type"`
	Severity     pgtype.Text     `json:"severity"`
	Payload      json.RawMessage `json:"payload"`
	IngestedAt   time.Time       `json:"ingested_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}
