// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentConfig struct {
	ID                   int32       `json:"id"`
	Model                string      `json:"model"`
	Mode                 string      `json:"mode"`
	Schedule             pgtype.Text `json:"schedule"`
	SystemPromptOverride pgtype.Text `json:"system_prompt_override"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
}

type AgentLog struct {
	ID             uuid.UUID   `json:"id"`
	UserID         uuid.UUID   `json:"user_id"`
	EntryType      string      `json:"entry_type"`
	Summary        string      `json:"summary"`
	Detail         []byte      `json:"detail"`
	Severity       pgtype.Text `json:"severity"`
	ConversationID pgtype.UUID `json:"conversation_id"`
	CreatedAt      time.Time   `json:"created_at"`
	AppID          pgtype.UUID `json:"app_id"`
}

type AppAgentConfig struct {
	AppID                uuid.UUID   `json:"app_id"`
	Model                string      `json:"model"`
	Mode                 string      `json:"mode"`
	ScheduleIntervalSecs int32       `json:"schedule_interval_secs"`
	SystemPromptOverride pgtype.Text `json:"system_prompt_override"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
	Provider             string      `json:"provider"`
}

type Application struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"org_id"`
	Name      string    `json:"name"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Connection struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Type      string          `json:"type"`
	Direction string          `json:"direction"`
	Config    json.RawMessage `json:"config"`
	Status    string          `json:"status"`
	LastSeen  *time.Time      `json:"last_seen"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
	UserID    uuid.UUID       `json:"user_id"`
	AppID     uuid.UUID       `json:"app_id"`
}

type Conversation struct {
	ID              uuid.UUID       `json:"id"`
	InvestigationID pgtype.UUID     `json:"investigation_id"`
	Title           pgtype.Text     `json:"title"`
	Messages        json.RawMessage `json:"messages"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
	UserID          uuid.UUID       `json:"user_id"`
}

type GithubRepo struct {
	ID            uuid.UUID `json:"id"`
	ConnectionID  uuid.UUID `json:"connection_id"`
	RepoFullName  string    `json:"repo_full_name"`
	RepoID        int64     `json:"repo_id"`
	DefaultBranch string    `json:"default_branch"`
	Enabled       bool      `json:"enabled"`
	CreatedAt     time.Time `json:"created_at"`
}

type Investigation struct {
	ID            uuid.UUID       `json:"id"`
	TriggerType   string          `json:"trigger_type"`
	TriggerSource pgtype.Text     `json:"trigger_source"`
	Summary       string          `json:"summary"`
	Severity      string          `json:"severity"`
	Status        string          `json:"status"`
	Context       json.RawMessage `json:"context"`
	Findings      []byte          `json:"findings"`
	ToolTrace     []byte          `json:"tool_trace"`
	Resolution    pgtype.Text     `json:"resolution"`
	StartedAt     time.Time       `json:"started_at"`
	ResolvedAt    *time.Time      `json:"resolved_at"`
	UserID        uuid.UUID       `json:"user_id"`
}

type InvestigationSchedule struct {
	ID           uuid.UUID   `json:"id"`
	AppID        uuid.UUID   `json:"app_id"`
	Name         string      `json:"name"`
	Prompt       string      `json:"prompt"`
	IntervalSecs int32       `json:"interval_secs"`
	CronExpr     pgtype.Text `json:"cron_expr"`
	Enabled      bool        `json:"enabled"`
	LastRunAt    *time.Time  `json:"last_run_at"`
	LastStatus   pgtype.Text `json:"last_status"`
	LastError    pgtype.Text `json:"last_error"`
	LastSummary  pgtype.Text `json:"last_summary"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type LogBuffer struct {
	ID           uuid.UUID       `json:"id"`
	ConnectionID uuid.UUID       `json:"connection_id"`
	SourceType   string          `json:"source_type"`
	Severity     pgtype.Text     `json:"severity"`
	Payload      json.RawMessage `json:"payload"`
	IngestedAt   time.Time       `json:"ingested_at"`
	UserID       uuid.UUID       `json:"user_id"`
	AppID        pgtype.UUID     `json:"app_id"`
}

type MonitoringState struct {
	AppID           uuid.UUID `json:"app_id"`
	LastMonitoredAt time.Time `json:"last_monitored_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type NotificationChannel struct {
	ID        uuid.UUID       `json:"id"`
	AppID     uuid.UUID       `json:"app_id"`
	Type      string          `json:"type"`
	Name      string          `json:"name"`
	Config    json.RawMessage `json:"config"`
	Enabled   bool            `json:"enabled"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type NotificationLog struct {
	ID           uuid.UUID   `json:"id"`
	AppID        uuid.UUID   `json:"app_id"`
	ChannelID    uuid.UUID   `json:"channel_id"`
	AgentLogID   pgtype.UUID `json:"agent_log_id"`
	Severity     string      `json:"severity"`
	Summary      string      `json:"summary"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
	SentAt       *time.Time  `json:"sent_at"`
	CreatedAt    time.Time   `json:"created_at"`
}

type NotificationPreference struct {
	AppID             uuid.UUID `json:"app_id"`
	Enabled           bool      `json:"enabled"`
	SeverityThreshold string    `json:"severity_threshold"`
	CooldownMinutes   int32     `json:"cooldown_minutes"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type Organization struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID   `json:"id"`
	Email     string      `json:"email"`
	CreatedAt time.Time   `json:"created_at"`
	OrgID     pgtype.UUID `json:"org_id"`
}
