// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OrgMemberRole string

const (
	OrgMemberRoleOwner  OrgMemberRole = "owner"
	OrgMemberRoleAdmin  OrgMemberRole = "admin"
	OrgMemberRoleMember OrgMemberRole = "member"
)

func (e *OrgMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrgMemberRole(s)
	case string:
		*e = OrgMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for OrgMemberRole: %T", src)
	}
	return nil
}

type NullOrgMemberRole struct {
	OrgMemberRole OrgMemberRole `json:"org_member_role"`
	Valid         bool          `json:"valid"` // Valid is true if OrgMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrgMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.OrgMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrgMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrgMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrgMemberRole), nil
}

type AgentConfig struct {
	ID                   int32       `json:"id"`
	Model                string      `json:"model"`
	Mode                 string      `json:"mode"`
	Schedule             pgtype.Text `json:"schedule"`
	SystemPromptOverride pgtype.Text `json:"system_prompt_override"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
}

type AgentLog struct {
	ID             uuid.UUID       `json:"id"`
	UserID         uuid.UUID       `json:"user_id"`
	EntryType      string          `json:"entry_type"`
	Summary        string          `json:"summary"`
	Detail         json.RawMessage `json:"detail"`
	Severity       pgtype.Text     `json:"severity"`
	ConversationID *uuid.UUID      `json:"conversation_id"`
	CreatedAt      time.Time       `json:"created_at"`
	AppID          uuid.UUID       `json:"app_id"`
}

type AppAgentConfig struct {
	AppID                uuid.UUID   `json:"app_id"`
	Model                string      `json:"model"`
	Mode                 string      `json:"mode"`
	ScheduleIntervalSecs int32       `json:"schedule_interval_secs"`
	SystemPromptOverride pgtype.Text `json:"system_prompt_override"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
	Provider             string      `json:"provider"`
}

type AppSourceFilter struct {
	ID           uuid.UUID `json:"id"`
	AppID        uuid.UUID `json:"app_id"`
	ConnectionID uuid.UUID `json:"connection_id"`
	SourceName   string    `json:"source_name"`
	Enabled      bool      `json:"enabled"`
	CreatedAt    time.Time `json:"created_at"`
}

type Application struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"org_id"`
	Name      string    `json:"name"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Connection struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Type      string          `json:"type"`
	Direction string          `json:"direction"`
	Config    json.RawMessage `json:"config"`
	Status    string          `json:"status"`
	LastSeen  *time.Time      `json:"last_seen"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
	UserID    uuid.UUID       `json:"user_id"`
	AppID     *uuid.UUID      `json:"app_id"`
	OrgID     uuid.UUID       `json:"org_id"`
}

type ConnectionSource struct {
	ID           uuid.UUID `json:"id"`
	ConnectionID uuid.UUID `json:"connection_id"`
	SourceName   string    `json:"source_name"`
	FirstSeenAt  time.Time `json:"first_seen_at"`
	LastSeenAt   time.Time `json:"last_seen_at"`
}

type Conversation struct {
	ID              uuid.UUID       `json:"id"`
	InvestigationID *uuid.UUID      `json:"investigation_id"`
	Title           pgtype.Text     `json:"title"`
	Messages        json.RawMessage `json:"messages"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
	UserID          uuid.UUID       `json:"user_id"`
}

type Investigation struct {
	ID            uuid.UUID       `json:"id"`
	TriggerType   string          `json:"trigger_type"`
	TriggerSource pgtype.Text     `json:"trigger_source"`
	Summary       string          `json:"summary"`
	Severity      string          `json:"severity"`
	Status        string          `json:"status"`
	Context       json.RawMessage `json:"context"`
	Findings      json.RawMessage `json:"findings"`
	ToolTrace     json.RawMessage `json:"tool_trace"`
	Resolution    pgtype.Text     `json:"resolution"`
	StartedAt     time.Time       `json:"started_at"`
	ResolvedAt    *time.Time      `json:"resolved_at"`
	UserID        uuid.UUID       `json:"user_id"`
}

type InvestigationSchedule struct {
	ID           uuid.UUID   `json:"id"`
	AppID        uuid.UUID   `json:"app_id"`
	Name         string      `json:"name"`
	Prompt       string      `json:"prompt"`
	IntervalSecs int32       `json:"interval_secs"`
	CronExpr     pgtype.Text `json:"cron_expr"`
	Enabled      bool        `json:"enabled"`
	LastRunAt    *time.Time  `json:"last_run_at"`
	LastStatus   pgtype.Text `json:"last_status"`
	LastError    pgtype.Text `json:"last_error"`
	LastSummary  pgtype.Text `json:"last_summary"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type LogBuffer struct {
	ID           uuid.UUID       `json:"id"`
	ConnectionID uuid.UUID       `json:"connection_id"`
	SourceType   string          `json:"source_type"`
	Severity     pgtype.Text     `json:"severity"`
	Payload      json.RawMessage `json:"payload"`
	IngestedAt   time.Time       `json:"ingested_at"`
	UserID       uuid.UUID       `json:"user_id"`
	AppID        uuid.UUID       `json:"app_id"`
}

type LogPipelineEvent struct {
	ID           uuid.UUID       `json:"id"`
	LogID        uuid.UUID       `json:"log_id"`
	AppID        uuid.UUID       `json:"app_id"`
	Stage        string          `json:"stage"`
	OccurredAt   time.Time       `json:"occurred_at"`
	SourceType   pgtype.Text     `json:"source_type"`
	Severity     pgtype.Text     `json:"severity"`
	Type         pgtype.Text     `json:"type"`
	Category     pgtype.Text     `json:"category"`
	Confidence   pgtype.Float8   `json:"confidence"`
	Summary      pgtype.Text     `json:"summary"`
	Escalated    pgtype.Bool     `json:"escalated"`
	RuleHit      pgtype.Text     `json:"rule_hit"`
	AssessmentID *uuid.UUID      `json:"assessment_id"`
	Metadata     json.RawMessage `json:"metadata"`
}

type MonitoringState struct {
	AppID           uuid.UUID `json:"app_id"`
	LastMonitoredAt time.Time `json:"last_monitored_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type NotificationChannel struct {
	ID        uuid.UUID       `json:"id"`
	AppID     uuid.UUID       `json:"app_id"`
	Type      string          `json:"type"`
	Name      string          `json:"name"`
	Config    json.RawMessage `json:"config"`
	Enabled   bool            `json:"enabled"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type NotificationLog struct {
	ID           uuid.UUID   `json:"id"`
	AppID        uuid.UUID   `json:"app_id"`
	ChannelID    uuid.UUID   `json:"channel_id"`
	AgentLogID   *uuid.UUID  `json:"agent_log_id"`
	Severity     string      `json:"severity"`
	Summary      string      `json:"summary"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
	SentAt       *time.Time  `json:"sent_at"`
	CreatedAt    time.Time   `json:"created_at"`
}

type NotificationPreference struct {
	AppID             uuid.UUID `json:"app_id"`
	Enabled           bool      `json:"enabled"`
	SeverityThreshold string    `json:"severity_threshold"`
	CooldownMinutes   int32     `json:"cooldown_minutes"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type OrgMember struct {
	UserID    uuid.UUID     `json:"user_id"`
	OrgID     uuid.UUID     `json:"org_id"`
	Role      OrgMemberRole `json:"role"`
	CreatedAt time.Time     `json:"created_at"`
}

type Organization struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

type WebhookIdempotency struct {
	ConnectionID   uuid.UUID       `json:"connection_id"`
	IdempotencyKey string          `json:"idempotency_key"`
	ResponseStatus int32           `json:"response_status"`
	ResponseBody   json.RawMessage `json:"response_body"`
	CreatedAt      time.Time       `json:"created_at"`
}
