// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitoring.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getMonitoringState = `-- name: GetMonitoringState :one
SELECT app_id, last_monitored_at, updated_at FROM monitoring_state WHERE app_id = $1
`

func (q *Queries) GetMonitoringState(ctx context.Context, appID uuid.UUID) (MonitoringState, error) {
	row := q.db.QueryRow(ctx, getMonitoringState, appID)
	var i MonitoringState
	err := row.Scan(&i.AppID, &i.LastMonitoredAt, &i.UpdatedAt)
	return i, err
}

const listActiveApplications = `-- name: ListActiveApplications :many
SELECT a.id, a.org_id, a.name, c.mode, c.schedule_interval_secs
FROM applications a
JOIN app_agent_config c ON c.app_id = a.id
WHERE a.status = 'active'
  AND c.mode != 'off'
  AND EXISTS (
      SELECT 1 FROM connections conn
      WHERE conn.app_id = a.id AND conn.status = 'active'
  )
`

type ListActiveApplicationsRow struct {
	ID                   uuid.UUID `json:"id"`
	OrgID                uuid.UUID `json:"org_id"`
	Name                 string    `json:"name"`
	Mode                 string    `json:"mode"`
	ScheduleIntervalSecs int32     `json:"schedule_interval_secs"`
}

func (q *Queries) ListActiveApplications(ctx context.Context) ([]ListActiveApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listActiveApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveApplicationsRow{}
	for rows.Next() {
		var i ListActiveApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Mode,
			&i.ScheduleIntervalSecs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogsSinceForApp = `-- name: ListLogsSinceForApp :many
SELECT id, connection_id, source_type, severity, payload, ingested_at, user_id, app_id FROM log_buffer
WHERE app_id = $1 AND ingested_at > $2
ORDER BY ingested_at ASC
LIMIT $3
`

type ListLogsSinceForAppParams struct {
	AppID      uuid.UUID `json:"app_id"`
	IngestedAt time.Time `json:"ingested_at"`
	Limit      int32     `json:"limit"`
}

func (q *Queries) ListLogsSinceForApp(ctx context.Context, arg ListLogsSinceForAppParams) ([]LogBuffer, error) {
	rows, err := q.db.Query(ctx, listLogsSinceForApp, arg.AppID, arg.IngestedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogBuffer{}
	for rows.Next() {
		var i LogBuffer
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.SourceType,
			&i.Severity,
			&i.Payload,
			&i.IngestedAt,
			&i.UserID,
			&i.AppID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetMonitoringCursor = `-- name: ResetMonitoringCursor :exec
INSERT INTO monitoring_state (app_id, last_monitored_at, updated_at)
VALUES ($1, now(), now())
ON CONFLICT (app_id) DO UPDATE
SET last_monitored_at = now(), updated_at = now()
`

func (q *Queries) ResetMonitoringCursor(ctx context.Context, appID uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetMonitoringCursor, appID)
	return err
}

const upsertMonitoringState = `-- name: UpsertMonitoringState :exec
INSERT INTO monitoring_state (app_id, last_monitored_at, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (app_id) DO UPDATE
SET last_monitored_at = $2, updated_at = now()
`

type UpsertMonitoringStateParams struct {
	AppID           uuid.UUID `json:"app_id"`
	LastMonitoredAt time.Time `json:"last_monitored_at"`
}

func (q *Queries) UpsertMonitoringState(ctx context.Context, arg UpsertMonitoringStateParams) error {
	_, err := q.db.Exec(ctx, upsertMonitoringState, arg.AppID, arg.LastMonitoredAt)
	return err
}
