// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_channels.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createNotificationChannel = `-- name: CreateNotificationChannel :one
INSERT INTO notification_channels (app_id, type, name, config, enabled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, app_id, type, name, config, enabled, created_at, updated_at
`

type CreateNotificationChannelParams struct {
	AppID   uuid.UUID       `json:"app_id"`
	Type    string          `json:"type"`
	Name    string          `json:"name"`
	Config  json.RawMessage `json:"config"`
	Enabled bool            `json:"enabled"`
}

func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, createNotificationChannel,
		arg.AppID,
		arg.Type,
		arg.Name,
		arg.Config,
		arg.Enabled,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Type,
		&i.Name,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNotificationChannel = `-- name: DeleteNotificationChannel :exec
DELETE FROM notification_channels WHERE id = $1
`

func (q *Queries) DeleteNotificationChannel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNotificationChannel, id)
	return err
}

const getNotificationChannel = `-- name: GetNotificationChannel :one
SELECT id, app_id, type, name, config, enabled, created_at, updated_at FROM notification_channels
WHERE id = $1
`

func (q *Queries) GetNotificationChannel(ctx context.Context, id uuid.UUID) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannel, id)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Type,
		&i.Name,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledChannelsByApp = `-- name: ListEnabledChannelsByApp :many
SELECT id, app_id, type, name, config, enabled, created_at, updated_at FROM notification_channels
WHERE app_id = $1 AND enabled = true
`

func (q *Queries) ListEnabledChannelsByApp(ctx context.Context, appID uuid.UUID) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listEnabledChannelsByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Type,
			&i.Name,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannelsByApp = `-- name: ListNotificationChannelsByApp :many
SELECT id, app_id, type, name, config, enabled, created_at, updated_at FROM notification_channels
WHERE app_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListNotificationChannelsByApp(ctx context.Context, appID uuid.UUID) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listNotificationChannelsByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Type,
			&i.Name,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationChannel = `-- name: UpdateNotificationChannel :one
UPDATE notification_channels
SET name = $2, config = $3, enabled = $4, updated_at = now()
WHERE id = $1
RETURNING id, app_id, type, name, config, enabled, created_at, updated_at
`

type UpdateNotificationChannelParams struct {
	ID      uuid.UUID       `json:"id"`
	Name    string          `json:"name"`
	Config  json.RawMessage `json:"config"`
	Enabled bool            `json:"enabled"`
}

func (q *Queries) UpdateNotificationChannel(ctx context.Context, arg UpdateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, updateNotificationChannel,
		arg.ID,
		arg.Name,
		arg.Config,
		arg.Enabled,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Type,
		&i.Name,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
