// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_preferences.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getNotificationPreferences = `-- name: GetNotificationPreferences :one
SELECT app_id, enabled, severity_threshold, cooldown_minutes, created_at, updated_at FROM notification_preferences WHERE app_id = $1
`

func (q *Queries) GetNotificationPreferences(ctx context.Context, appID uuid.UUID) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, getNotificationPreferences, appID)
	var i NotificationPreference
	err := row.Scan(
		&i.AppID,
		&i.Enabled,
		&i.SeverityThreshold,
		&i.CooldownMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNotificationPreferences = `-- name: UpsertNotificationPreferences :one
INSERT INTO notification_preferences (app_id, enabled, severity_threshold, cooldown_minutes)
VALUES ($1, $2, $3, $4)
ON CONFLICT (app_id) DO UPDATE
SET enabled = EXCLUDED.enabled,
    severity_threshold = EXCLUDED.severity_threshold,
    cooldown_minutes = EXCLUDED.cooldown_minutes,
    updated_at = now()
RETURNING app_id, enabled, severity_threshold, cooldown_minutes, created_at, updated_at
`

type UpsertNotificationPreferencesParams struct {
	AppID             uuid.UUID `json:"app_id"`
	Enabled           bool      `json:"enabled"`
	SeverityThreshold string    `json:"severity_threshold"`
	CooldownMinutes   int32     `json:"cooldown_minutes"`
}

func (q *Queries) UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreferences,
		arg.AppID,
		arg.Enabled,
		arg.SeverityThreshold,
		arg.CooldownMinutes,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.AppID,
		&i.Enabled,
		&i.SeverityThreshold,
		&i.CooldownMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
