// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_log.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLastNotificationForApp = `-- name: GetLastNotificationForApp :one
SELECT id, app_id, channel_id, agent_log_id, severity, summary, status, error_message, sent_at, created_at FROM notification_log
WHERE app_id = $1 AND status = 'sent'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastNotificationForApp(ctx context.Context, appID uuid.UUID) (NotificationLog, error) {
	row := q.db.QueryRow(ctx, getLastNotificationForApp, appID)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ChannelID,
		&i.AgentLogID,
		&i.Severity,
		&i.Summary,
		&i.Status,
		&i.ErrorMessage,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertNotificationLog = `-- name: InsertNotificationLog :one
INSERT INTO notification_log (app_id, channel_id, agent_log_id, severity, summary, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, app_id, channel_id, agent_log_id, severity, summary, status, error_message, sent_at, created_at
`

type InsertNotificationLogParams struct {
	AppID      uuid.UUID  `json:"app_id"`
	ChannelID  uuid.UUID  `json:"channel_id"`
	AgentLogID *uuid.UUID `json:"agent_log_id"`
	Severity   string     `json:"severity"`
	Summary    string     `json:"summary"`
	Status     string     `json:"status"`
}

func (q *Queries) InsertNotificationLog(ctx context.Context, arg InsertNotificationLogParams) (NotificationLog, error) {
	row := q.db.QueryRow(ctx, insertNotificationLog,
		arg.AppID,
		arg.ChannelID,
		arg.AgentLogID,
		arg.Severity,
		arg.Summary,
		arg.Status,
	)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ChannelID,
		&i.AgentLogID,
		&i.Severity,
		&i.Summary,
		&i.Status,
		&i.ErrorMessage,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationLogByApp = `-- name: ListNotificationLogByApp :many
SELECT nl.id, nl.app_id, nl.channel_id, nl.agent_log_id, nl.severity, nl.summary, nl.status, nl.error_message, nl.sent_at, nl.created_at, nc.type AS channel_type, nc.name AS channel_name
FROM notification_log nl
JOIN notification_channels nc ON nc.id = nl.channel_id
WHERE nl.app_id = $1
ORDER BY nl.created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationLogByAppParams struct {
	AppID  uuid.UUID `json:"app_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListNotificationLogByAppRow struct {
	ID           uuid.UUID   `json:"id"`
	AppID        uuid.UUID   `json:"app_id"`
	ChannelID    uuid.UUID   `json:"channel_id"`
	AgentLogID   *uuid.UUID  `json:"agent_log_id"`
	Severity     string      `json:"severity"`
	Summary      string      `json:"summary"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
	SentAt       *time.Time  `json:"sent_at"`
	CreatedAt    time.Time   `json:"created_at"`
	ChannelType  string      `json:"channel_type"`
	ChannelName  string      `json:"channel_name"`
}

func (q *Queries) ListNotificationLogByApp(ctx context.Context, arg ListNotificationLogByAppParams) ([]ListNotificationLogByAppRow, error) {
	rows, err := q.db.Query(ctx, listNotificationLogByApp, arg.AppID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationLogByAppRow{}
	for rows.Next() {
		var i ListNotificationLogByAppRow
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.ChannelID,
			&i.AgentLogID,
			&i.Severity,
			&i.Summary,
			&i.Status,
			&i.ErrorMessage,
			&i.SentAt,
			&i.CreatedAt,
			&i.ChannelType,
			&i.ChannelName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationLogStatus = `-- name: UpdateNotificationLogStatus :exec
UPDATE notification_log
SET status = $2, error_message = $3, sent_at = CASE WHEN $2 = 'sent' THEN now() ELSE sent_at END
WHERE id = $1
`

type UpdateNotificationLogStatusParams struct {
	ID           uuid.UUID   `json:"id"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateNotificationLogStatus(ctx context.Context, arg UpdateNotificationLogStatusParams) error {
	_, err := q.db.Exec(ctx, updateNotificationLogStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}
