// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: source_filters.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countAppSourceFilters = `-- name: CountAppSourceFilters :one
SELECT count(*) FROM app_source_filters
WHERE app_id = $1 AND connection_id = $2
`

type CountAppSourceFiltersParams struct {
	AppID        uuid.UUID `json:"app_id"`
	ConnectionID uuid.UUID `json:"connection_id"`
}

// CountAppSourceFilters counts all filter rows for an (app, connection)
// pair. Used by the ingestion handler to distinguish "no filters exist yet"
// (drop-by-default) from "filters exist but none enabled" (also drops, but
// the UI can surface a different message).
func (q *Queries) CountAppSourceFilters(ctx context.Context, arg CountAppSourceFiltersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAppSourceFilters, arg.AppID, arg.ConnectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAppSourceFilter = `-- name: DeleteAppSourceFilter :exec
DELETE FROM app_source_filters
WHERE app_id = $1 AND connection_id = $2 AND source_name = $3
`

type DeleteAppSourceFilterParams struct {
	AppID        uuid.UUID `json:"app_id"`
	ConnectionID uuid.UUID `json:"connection_id"`
	SourceName   string    `json:"source_name"`
}

// DeleteAppSourceFilter removes a filter row entirely. Distinct from toggling
// enabled=false: this is only used for manually-added sources that the user
// wants to forget. Auto-discovered sources should be toggled off, not deleted.
func (q *Queries) DeleteAppSourceFilter(ctx context.Context, arg DeleteAppSourceFilterParams) error {
	_, err := q.db.Exec(ctx, deleteAppSourceFilter, arg.AppID, arg.ConnectionID, arg.SourceName)
	return err
}

const listAppSourceFilters = `-- name: ListAppSourceFilters :many

SELECT id, app_id, connection_id, source_name, enabled, created_at FROM app_source_filters
WHERE app_id = $1 AND connection_id = $2
ORDER BY source_name
`

type ListAppSourceFiltersParams struct {
	AppID        uuid.UUID `json:"app_id"`
	ConnectionID uuid.UUID `json:"connection_id"`
}

// --------------------------------------------------------------------------
// app_source_filters — per-app enable/disable
// --------------------------------------------------------------------------
// ListAppSourceFilters returns the filter rows for a given (app, connection)
// pair. Only these rows are authoritative — missing rows mean "not configured"
// and are treated as disabled by the ingestion handler (drop-by-default).
func (q *Queries) ListAppSourceFilters(ctx context.Context, arg ListAppSourceFiltersParams) ([]AppSourceFilter, error) {
	rows, err := q.db.Query(ctx, listAppSourceFilters, arg.AppID, arg.ConnectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSourceFilter{}
	for rows.Next() {
		var i AppSourceFilter
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.ConnectionID,
			&i.SourceName,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectionSources = `-- name: ListConnectionSources :many
SELECT id, connection_id, source_name, first_seen_at, last_seen_at FROM connection_sources
WHERE connection_id = $1
ORDER BY last_seen_at DESC
`

// ListConnectionSources returns every source ever seen on a connection,
// ordered by recency. Used to render the discovery half of the source
// selector UI.
func (q *Queries) ListConnectionSources(ctx context.Context, connectionID uuid.UUID) ([]ConnectionSource, error) {
	rows, err := q.db.Query(ctx, listConnectionSources, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectionSource{}
	for rows.Next() {
		var i ConnectionSource
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.SourceName,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledGitHubReposByApp = `-- name: ListEnabledGitHubReposByApp :many

SELECT
    c.id               AS connection_id,
    asf.source_name    AS repo_full_name,
    c.config           AS connection_config
FROM app_source_filters asf
JOIN connections c ON c.id = asf.connection_id
WHERE asf.app_id = $1
  AND asf.enabled = true
  AND c.type = 'github'
  AND c.status = 'active'
ORDER BY asf.source_name
`

type ListEnabledGitHubReposByAppRow struct {
	ConnectionID     uuid.UUID       `json:"connection_id"`
	RepoFullName     string          `json:"repo_full_name"`
	ConnectionConfig json.RawMessage `json:"connection_config"`
}

// --------------------------------------------------------------------------
// Connector-specific projections over the generic tables
// --------------------------------------------------------------------------
// ListEnabledGitHubReposByApp replaces the pre-Phase-3 query of the same
// name that read from the bespoke github_repos table. GitHub repos are now
// just rows in app_source_filters whose parent connection has type='github'
// — the agent's search_codebase tool joins through here to resolve repo
// full names plus the connection's installation config.
//
// Returns the connection id (so callers can group by installation), the
// repo full name, and the connection's config (for installation_id lookup).
func (q *Queries) ListEnabledGitHubReposByApp(ctx context.Context, appID uuid.UUID) ([]ListEnabledGitHubReposByAppRow, error) {
	rows, err := q.db.Query(ctx, listEnabledGitHubReposByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledGitHubReposByAppRow{}
	for rows.Next() {
		var i ListEnabledGitHubReposByAppRow
		if err := rows.Scan(&i.ConnectionID, &i.RepoFullName, &i.ConnectionConfig); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledSourceNames = `-- name: ListEnabledSourceNames :many
SELECT source_name FROM app_source_filters
WHERE connection_id = $1 AND app_id = $2 AND enabled = true
`

type ListEnabledSourceNamesParams struct {
	ConnectionID uuid.UUID `json:"connection_id"`
	AppID        uuid.UUID `json:"app_id"`
}

// ListEnabledSourceNames is the ingestion-hot-path query. Called once per
// webhook batch to load the set of enabled source names for a connection's
// app. Backed by idx_app_source_filters_app_lookup (migration 037: partial
// index on (connection_id, app_id) WHERE enabled = true) so the planner
// can index-only scan on both filter columns without a heap re-check.
// The older idx_app_source_filters_lookup (connection_id, source_name)
// partial index still exists — it serves ListAppsEnabledForSource's
// org-fan-out access pattern. Both indexes are small and justified.
func (q *Queries) ListEnabledSourceNames(ctx context.Context, arg ListEnabledSourceNamesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listEnabledSourceNames, arg.ConnectionID, arg.AppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var source_name string
		if err := rows.Scan(&source_name); err != nil {
			return nil, err
		}
		items = append(items, source_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAppSourceFilter = `-- name: UpsertAppSourceFilter :one
INSERT INTO app_source_filters (app_id, connection_id, source_name, enabled)
VALUES ($1, $2, $3, $4)
ON CONFLICT (app_id, connection_id, source_name)
DO UPDATE SET enabled = EXCLUDED.enabled
RETURNING id, app_id, connection_id, source_name, enabled, created_at
`

type UpsertAppSourceFilterParams struct {
	AppID        uuid.UUID `json:"app_id"`
	ConnectionID uuid.UUID `json:"connection_id"`
	SourceName   string    `json:"source_name"`
	Enabled      bool      `json:"enabled"`
}

// UpsertAppSourceFilter toggles a single source on/off for a given app.
// Used by both bulk PUT (one call per item) and the manual POST add path.
func (q *Queries) UpsertAppSourceFilter(ctx context.Context, arg UpsertAppSourceFilterParams) (AppSourceFilter, error) {
	row := q.db.QueryRow(ctx, upsertAppSourceFilter,
		arg.AppID,
		arg.ConnectionID,
		arg.SourceName,
		arg.Enabled,
	)
	var i AppSourceFilter
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ConnectionID,
		&i.SourceName,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const upsertConnectionSource = `-- name: UpsertConnectionSource :one

INSERT INTO connection_sources (connection_id, source_name)
VALUES ($1, $2)
ON CONFLICT (connection_id, source_name)
DO UPDATE SET last_seen_at = now()
RETURNING id, connection_id, source_name, first_seen_at, last_seen_at
`

type UpsertConnectionSourceParams struct {
	ConnectionID uuid.UUID `json:"connection_id"`
	SourceName   string    `json:"source_name"`
}

// --------------------------------------------------------------------------
// connection_sources — auto-discovery ledger
// --------------------------------------------------------------------------
// UpsertConnectionSource records that a source name was seen for a
// connection. Called from ingestion after the payload is parsed; `last_seen_at`
// refreshes on every call so staleness ticks down while traffic flows.
func (q *Queries) UpsertConnectionSource(ctx context.Context, arg UpsertConnectionSourceParams) (ConnectionSource, error) {
	row := q.db.QueryRow(ctx, upsertConnectionSource, arg.ConnectionID, arg.SourceName)
	var i ConnectionSource
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.SourceName,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}
