// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getAppDashboardStats = `-- name: GetAppDashboardStats :one
SELECT
  (SELECT count(*) FROM log_buffer lb WHERE lb.app_id = $1 AND lb.ingested_at > now() - interval '24 hours')::bigint AS log_count_24h,
  (SELECT count(*) FROM connections c WHERE c.app_id = $1)::bigint AS connection_count,
  (SELECT count(*) FROM connections c2 WHERE c2.app_id = $1 AND c2.status = 'active')::bigint AS active_connections
`

type GetAppDashboardStatsRow struct {
	LogCount24h       int64 `json:"log_count_24h"`
	ConnectionCount   int64 `json:"connection_count"`
	ActiveConnections int64 `json:"active_connections"`
}

func (q *Queries) GetAppDashboardStats(ctx context.Context, appID uuid.UUID) (GetAppDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getAppDashboardStats, appID)
	var i GetAppDashboardStatsRow
	err := row.Scan(&i.LogCount24h, &i.ConnectionCount, &i.ActiveConnections)
	return i, err
}
