// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getFirstUserInOrg = `-- name: GetFirstUserInOrg :one
SELECT om.user_id AS id FROM org_members om
WHERE om.org_id = $1
ORDER BY om.created_at ASC LIMIT 1
`

func (q *Queries) GetFirstUserInOrg(ctx context.Context, orgID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getFirstUserInOrg, orgID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const hasOrgMembership = `-- name: HasOrgMembership :one
SELECT EXISTS(SELECT 1 FROM org_members WHERE user_id = $1) AS has_org
`

// Returns true if the user belongs to any organization.
// Used by the onboarding idempotency guard (replaces old user.OrgID.Valid check).
func (q *Queries) HasOrgMembership(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasOrgMembership, userID)
	var has_org bool
	err := row.Scan(&has_org)
	return has_org, err
}
