// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhook_idempotency.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getIdempotencyResult = `-- name: GetIdempotencyResult :one
SELECT response_status, response_body FROM webhook_idempotency
WHERE connection_id = $1 AND idempotency_key = $2 AND created_at > now() - interval '24 hours'
`

type GetIdempotencyResultParams struct {
	ConnectionID   uuid.UUID `json:"connection_id"`
	IdempotencyKey string    `json:"idempotency_key"`
}

type GetIdempotencyResultRow struct {
	ResponseStatus int32           `json:"response_status"`
	ResponseBody   json.RawMessage `json:"response_body"`
}

func (q *Queries) GetIdempotencyResult(ctx context.Context, arg GetIdempotencyResultParams) (GetIdempotencyResultRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyResult, arg.ConnectionID, arg.IdempotencyKey)
	var i GetIdempotencyResultRow
	err := row.Scan(&i.ResponseStatus, &i.ResponseBody)
	return i, err
}

const insertIdempotencyResult = `-- name: InsertIdempotencyResult :exec
INSERT INTO webhook_idempotency (connection_id, idempotency_key, response_status, response_body)
VALUES ($1, $2, $3, $4)
ON CONFLICT (connection_id, idempotency_key) DO NOTHING
`

type InsertIdempotencyResultParams struct {
	ConnectionID   uuid.UUID       `json:"connection_id"`
	IdempotencyKey string          `json:"idempotency_key"`
	ResponseStatus int32           `json:"response_status"`
	ResponseBody   json.RawMessage `json:"response_body"`
}

func (q *Queries) InsertIdempotencyResult(ctx context.Context, arg InsertIdempotencyResultParams) error {
	_, err := q.db.Exec(ctx, insertIdempotencyResult,
		arg.ConnectionID,
		arg.IdempotencyKey,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	return err
}

const pruneExpiredIdempotencyKeys = `-- name: PruneExpiredIdempotencyKeys :execrows
DELETE FROM webhook_idempotency WHERE created_at < now() - interval '24 hours'
`

func (q *Queries) PruneExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
